server.port: 7000

app:
  product-service:
    host: localhost
    port: 7002
  customer-service:
    host: localhost
    port: 7001
  service-service:
    host: localhost
    port: 7003

logging:
  level:
    root: INFO
    se.magnus: DEBUG

---
spring.profiles: docker

server.port: 8080

app:
  product-service:
    host: product
    port: 8080
  customer-service:
    host: customer
    port: 8080
  service-service:
    host: service
    port: 8080